### PR TITLE
Workaround pad problem on mps

### PR DESCRIPTION
**Pull request by niw**
When using `torch.nn.functional.pad` with tensor that size is larger than 2^16 (65526), the output tensor would be broken.
This patch moves tensor to CPU to workaround the problem. It doesn't too much impacts in terms of speed of vea on mps.

This patch solves the pyschederic frame image output on mps described on #43.

### CODE REVIEW

**Comment by niw** [comment]
Note that the root issue is, to me at this moment, unknown. It could be pytorch implementation, could be Apple’s MPSGraph itself.

**Comment by john2stai** [comment]
hmmmmmm, I got the error: Input type (float) and bias type (c10::BFloat16) should be the same. 

the input type and bias type flipped  as the original error.

**Comment by niw** [comment]
@john2stai See #67 for example, this patch is not solving dtype mismatch.

**Comment by john2stai** [comment]
ok, I thought by adding the codes would fix the error, but every time I added them into the files, the nodes all go missing.  Thank you for all your help! Greatly appreciated!

> @john2stai See #67 for example, this patch is not solving dtype mismatch.

ok, I thought by adding the codes would fix the error, but every time I added them into the files, the nodes all go missing.  Thank you for all your help! Greatly appreciated!

**Pull request merged**
